# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
np.version.version


'1.26.4'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:

a = np.random.randint(0 ,100, size=(2,3,5))



### 4. Print a.


In [5]:
print(a)

[[[22 42 93  9  1]
  [ 7 11 16 99 29]
  [13 88  0 24 58]]

 [[70 47 96 23 98]
  [40  3 16 67 71]
  [84 18 22 21 52]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
b = np.ones((5,2,3))


### 6. Print b.


In [7]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
print(a.size)
print(b.size)

if a.size == b.size:
    print("The size of a and b is the same")
else:
    print("The size of a and b is not the same")

30
30
The size of a and b is the same



### 8. Are you able to add a and b? Why or why not?


In [9]:
print(a.shape)
print(b.shape)
#because they have different structure they are not the same

(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
c = b.transpose(1, 2, 0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [11]:
d = np.add(a, c)
print(d)
print(d.shape)


[[[ 23.  43.  94.  10.   2.]
  [  8.  12.  17. 100.  30.]
  [ 14.  89.   1.  25.  59.]]

 [[ 71.  48.  97.  24.  99.]
  [ 41.   4.  17.  68.  72.]
  [ 85.  19.  23.  22.  53.]]]
(2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
print(a)
print("-")
print(d)

[[[22 42 93  9  1]
  [ 7 11 16 99 29]
  [13 88  0 24 58]]

 [[70 47 96 23 98]
  [40  3 16 67 71]
  [84 18 22 21 52]]]
-
[[[ 23.  43.  94.  10.   2.]
  [  8.  12.  17. 100.  30.]
  [ 14.  89.   1.  25.  59.]]

 [[ 71.  48.  97.  24.  99.]
  [ 41.   4.  17.  68.  72.]
  [ 85.  19.  23.  22.  53.]]]



### 12. Multiply a and c. Assign the result to e.


In [13]:
e = np.multiply(a, c)
print(e)

[[[22. 42. 93.  9.  1.]
  [ 7. 11. 16. 99. 29.]
  [13. 88.  0. 24. 58.]]

 [[70. 47. 96. 23. 98.]
  [40.  3. 16. 67. 71.]
  [84. 18. 22. 21. 52.]]]




### 13. Does e equal to a? Why or why not?


In [14]:
if (e == a).all():
    print("The arrays are equal")
else:
    print("The arrays are not equal")


The arrays are equal




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [15]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

100.0
1.0
42.333333333333336



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [16]:
f = np.empty((2,3,5))
print(f.shape)

(2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [17]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [18]:
print(d)
print("-")
print(f)

[[[ 23.  43.  94.  10.   2.]
  [  8.  12.  17. 100.  30.]
  [ 14.  89.   1.  25.  59.]]

 [[ 71.  48.  97.  24.  99.]
  [ 41.   4.  17.  68.  72.]
  [ 85.  19.  23.  22.  53.]]]
-
[[[ 25.  75.  75.  25.  25.]
  [ 25.  25.  25. 100.  25.]
  [ 25.  75.   0.  25.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [20]:
#array of Unicode strings
f = np.empty((2, 3, 5), dtype='U1')

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] == d_min:
                f[i,j,k] = 'A'  
            elif d[i,j,k] == d_max:
                f[i,j,k] = 'E'
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 'C'
            elif d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 'B'
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 'D'

print(f)

[[['B' 'D' 'D' 'B' 'B']
  ['B' 'B' 'B' 'E' 'B']
  ['B' 'D' 'A' 'B' 'D']]

 [['D' 'D' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']]]
